apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nucleus-prod
  name: nucleus-nodeport
  namespace: nucleus-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 31758
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: nucleus-prod
    type: cmd
  sessionAffinity: None
  type: NodePort
status:
  # existing ELB managed by tf not k8s
  loadBalancer: {}
